### ISSUE TITLE
[BUG] Wrong Zram Resizeing 

### ISSUE THREAD

**Issue by Yazed20** [lululoid/LMKD-PSI-Activator#2]
Zram Goes Fully disable or ( 0 zram ) 

[magisk_install_log_2024-07-31T12.30.15.log](https://github.com/user-attachments/files/16439351/magisk_install_log_2024-07-31T12.30.15.log)

![Screenshot_20240731-122846_DiskInfo](https://github.com/user-attachments/assets/1fc2fb54-33f3-4472-a147-123aeda86cf2)

**Comment by lululoid** [comment]
Could you send the log in `/data/adb/fmiop.log`

**Comment by Yazed20** [comment]
@lululoid 
[Uploading fmiop.log…]()

**Comment by Yazed20** [comment]
@lululoid 
[fmiop.log](https://github.com/user-attachments/files/16459473/fmiop.log)

**Comment by lululoid** [comment]
It's updated, it should be fixed now
